# Generated by Django 5.0.7 on 2024-07-29 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название рассылки')),
                ('time', models.DateField(verbose_name='Время начала отправки рассылки')),
                ('count', models.PositiveIntegerField(verbose_name='Количество рассылок')),
                ('period', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=255, verbose_name='Периодичность рассылки')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('inactive', 'Не активна')], max_length=255, verbose_name='Статус рассылки')),
                ('clients', models.ManyToManyField(related_name='mails', to='smm.client', verbose_name='Клиенты')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smm.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
